version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lingualeap_postgres
    environment:
      POSTGRES_DB: lingualeap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5