spring:
  application:
    name: lingualeap
  jpa:
    open-in-view: false

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:defaulSecretKeyForDevOnly}
      expiration: 86400000 # 1 day