name: CI/CD Pipeline

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: lingualeap_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and Test
        run: |
          chmod +x gradlew
          ./gradlew build -x test 

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports/tests/
            build/reports/jacoco/
            build/reports/checkstyle/
            build/reports/pmd/
          retention-days: 5

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t lingualeap:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag lingualeap:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/lingualeap:latest
          docker tag lingualeap:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/lingualeap:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lingualeap:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lingualeap:${{ github.sha }}